### ISSUE TITLE
Option to generate a struct without sorting fields

### ISSUE THREAD

**Issue by mf-sakura** [deepmap/oapi-codegen#458] opened 2021-10-07 04:50 UTC
I want to generate a struct without sorting fields, in the order listed in the OpenAPI doc.

I wrote my OpenAPI component schema so that the fields that are important to the user are at the top
And I want to return JSON fields on my server response in the same order.
However, for now, generated fields are sorted in increasing order.

So I want an option to generate a struct without sorting field.

openapi.yml
```yml
components:
  schemas:
    Pet:
      properties:
        id:
          type: integer
          format: int64
          description: Unique id of the pet
        name:
          type: string
          description: Name of the pet
        age:
          type: integer
          format: int64
          description: Age of the pet
```

Current
```go
// Pet defines model for Pet.
type Pet struct {
  // Age of the pet
  Age *int64 `json:"age,omitempty"`

  // Unique id of the pet
  Id *int64 `json:"id,omitempty"`

  // Name of the pet
  Name *string `json:"name,omitempty"`
}
```

What I want
```go
// Pet defines model for Pet.
type Pet struct {
  // Unique id of the pet
  Id *int64 `json:"id,omitempty"`

  // Name of the pet
  Name *string `json:"name,omitempty"`

  // Age of the pet
  Age *int64 `json:"age,omitempty"`
}
```

**Comment by weusego** [comment] 2022-03-25 15:30
+100 -

great job with oapi-codegen, but we are very irritated to see all the fields from our nicely designed structures appear in alphabetical order...

the underlying https://github.com/getkin/kin-openapi/ seems to be the problem, parsing it into a map where the ordering is lost.

**Comment by gnvk** [comment] 2022-06-02 05:30
@deepmap-marcinr Is there a way to fix / work around this?

**Comment by psyhatter** [comment] 2022-06-14 02:49
Often this problem is solved by the `x-order` extension, for example in https://github.com/go-openapi/spec or https://github.com/go-swagger/go-swagger

**Comment by goforbroke1006** [comment] 2022-06-15 21:02
I have check dependecy for parsing openapi specification - github.com/getkin/kin-openapi
openapi3/schema.go:156 - field that keep properties
openapi3/loader.go:159 - unmarshalling yaml to struct

Look like it is a behaviour of "github.com/invopop/yaml" unmarshalling mechanism.
I tried "gopkg.in/yaml.v3" , but does not work.

What suggestions how to fix it without writing a new yaml parser?

**Comment by renom** [comment] 2023-09-14 11:59
https://github.com/getkin/kin-openapi did use https://github.com/ghodss/yaml but they switched to https://github.com/invopop/yaml for some reason.
https://github.com/ghodss/yaml seems to keep the order of the fields when converted.

**Comment by renom** [comment] 2023-09-18 10:48
Well, it's somewhere inside [convertToJSONableObject](https://github.com/invopop/yaml/blob/main/yaml.go#L137) in [invopop/yaml](https://github.com/invopop/yaml) because [go-yaml/yaml](https://github.com/go-yaml/yaml) keeps the ordering when YAML is converted to map.

**Comment by renom** [comment] 2023-10-19 12:55
https://github.com/goccy/go-yaml
This library preserve the order. Would it be enough to replace [invopop/yaml](https://github.com/invopop/yaml) with [goccy/go-yaml](https://github.com/goccy/go-yaml)? It has the same method `func YAMLToJSON(bytes []byte) ([]byte, error)`

**Comment by DeOne4eg** [comment] 2023-12-17 19:11
The problem is relevant for me too. Are there any solutions?

**Comment by stijnderyckere** [comment] 2024-01-18 15:43
This also frustrates me the most about the oapi codegen. Are there any workarounds for this?

**Comment by jamietanna** [comment] 2024-01-25 12:24
:eyes:

**Comment by jamietanna** [comment] 2024-01-25 14:36
Closed by https://github.com/deepmap/oapi-codegen/commit/3bf5755366704a1594410d6a7aa7aab966d04c6e

**Closed by jamietanna** 2024-01-25 14:36 UTC
