### ISSUE TITLE
Cannot use a user-template for generation "api.go:193:1: expected declaration, found https"

### ISSUE THREAD

**Issue by lukaskirner** [deepmap/oapi-codegen#1256] opened 2023-09-11 14:42 UTC
Defining a user template will result into an error `: api.go:9986:1: expected declaration, found https`. Generation will work without setting the config. Using version `v1.15.0`

## Error output: 
```
go generate ./...
error generating code: error formatting Go code // Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
        "bytes"
        "compress/gzip"
        "context"
        "encoding/base64"
        "encoding/json"
        "encoding/xml"
        "errors"
        "fmt"
        "gopkg.in/yaml.v2"
        "io"
        "os"
        "net/http"
        "net/url"
        "path"
        "strings"
        "time"

        "github.com/deepmap/oapi-codegen/pkg/runtime"
        openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
        "github.com/getkin/kin-openapi/openapi3"
        "github.com/go-chi/chi/v5"
        "github.com/labstack/echo/v4"
        "github.com/gin-gonic/gin"
        "github.com/gorilla/mux"
)




// Defines values for State.
const (

  StateOFFLINE State = "OFFLINE"
  StateONLINE State = "ONLINE"
)


// State defines model for State.
type State  string










// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
        Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
        // The endpoint of the server conforming to this interface, with scheme,
        // https://api.deepmap.com for example. This can contain a path relative
        // to the server, such as https://api.deepmap.com/dev-test, and all the
        // paths in the swagger spec will be appended to the server.
        Server string

        // Doer for performing requests, typically a *http.Client with any
        // customized settings, such as certificate chains.
        Client HttpRequestDoer

        // A list of callbacks for modifying requests which are generated before sending over
        // the network.
        RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
    // create a client with sane default values
    client := Client{
        Server: server,
    }
    // mutate client and add all optional params
    for _, o := range opts {
        if err := o(&client); err != nil {
            return nil, err
        }
    }
    // ensure the server URL always has a trailing slash
    if !strings.HasSuffix(client.Server, "/") {
        client.Server += "/"
    }
    // create httpClient, if not already present
    if client.Client == nil {
        client.Client = &http.Client{}
    }
    return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
        return func(c *Client) error {
                c.Client = doer
                return nil
        }
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
        return func(c *Client) error {
                c.RequestEditors = append(c.RequestEditors, fn)
                return nil
        }
}

// The interface specification for the client above.
type ClientInterface interface {
// GetState request
    GetState(ctx context.Context, reqEditors... RequestEditorFn) (*http.Response, error)


}



func (c *Client) GetState(ctx context.Context, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewGetStateRequest(c.Server)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}








// NewGetStateRequest generates requests for GetState
func NewGetStateRequest(server string) (*http.Request, error) {
    var err error

    serverURL, err := url.Parse(server)
    if err != nil {
        return nil, err
    }

    operationPath := fmt.Sprintf("/edges")
    if operationPath[0] == '/' {
        operationPath = "." + operationPath
    }

    queryURL, err := serverURL.Parse(operationPath)
    if err != nil {
        return nil, err
    }


    req, err := http.NewRequest("GET", queryURL.String(), nil)
    if err != nil {
        return nil, err
    }

    



    return req, nil
}



func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
    for _, r := range c.RequestEditors {
        if err := r(ctx, req); err != nil {
            return err
        }
    }
    for _, r := range additionalEditors {
        if err := r(ctx, req); err != nil {
            return err
        }
    }
    return nil
}
https://raw.githubusercontent.com/deepmap/oapi-codegen/master/pkg/codegen/templates/client-with-responses.tmpl// ServerInterface represents all server handlers.
type ServerInterface interface {

// (GET /edges)
GetState(w http.ResponseWriter, r *http.Request)

}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
    Handler ServerInterface
    HandlerMiddlewares []MiddlewareFunc
    ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler



// GetState operation middleware
func (siw *ServerInterfaceWrapper) GetState(w http.ResponseWriter, r *http.Request) {
  ctx := r.Context()
  

  



  

  var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    siw.Handler.GetState(w, r)
  })

  
  for _, middleware := range siw.HandlerMiddlewares {
    handler = middleware(handler)
  }
  

  handler.ServeHTTP(w, r.WithContext(ctx))
}


type UnescapedCookieParamError struct {
    ParamName string
        Err error
}

func (e *UnescapedCookieParamError) Error() string {
    return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
    return e.Err
}

type UnmarshallingParamError struct {
    ParamName string
    Err error
}

func (e *UnmarshallingParamError) Error() string {
    return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
    return e.Err
}

type RequiredParamError struct {
    ParamName string
}

func (e *RequiredParamError) Error() string {
    return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
    ParamName string
    Err error
}

func (e *RequiredHeaderError) Error() string {
    return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
    return e.Err
}

type InvalidParamFormatError struct {
    ParamName string
          Err error
}

func (e *InvalidParamFormatError) Error() string {
    return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
    return e.Err
}

type TooManyValuesForParamError struct {
    ParamName string
    Count int
}

func (e *TooManyValuesForParamError) Error() string {
    return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
  return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
    BaseURL string
    BaseRouter chi.Router
    Middlewares []MiddlewareFunc
    ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
    return HandlerWithOptions(si, ChiServerOptions {
        BaseRouter: r,
    })
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
    return HandlerWithOptions(si, ChiServerOptions {
        BaseURL: baseURL,
        BaseRouter: r,
    })
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
r := options.BaseRouter

if r == nil {
r = chi.NewRouter()
}
if options.ErrorHandlerFunc == nil {
    options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
        http.Error(w, err.Error(), http.StatusBadRequest)
    }
}
wrapper := ServerInterfaceWrapper{
Handler: si,
HandlerMiddlewares: options.Middlewares,
ErrorHandlerFunc: options.ErrorHandlerFunc,
}

r.Group(func(r chi.Router) {
r.Get(options.BaseURL+"/edges", wrapper.GetState)
})

return r
}

    type GetStateRequestObject struct {
        }

    type GetStateResponseObject interface {
        VisitGetStateResponse(w http.ResponseWriter) error
    }

    
        

        

        type GetState200Response struct {
                    
                    }
            func (response GetState200Response) VisitGetStateResponse(w http.ResponseWriter) error {
                w.WriteHeader(200)
                return nil
            }
        
    


// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

// (GET /edges)
GetState(ctx context.Context, request GetStateRequestObject) (GetStateResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
    RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
    ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
    return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions {
        RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
            http.Error(w, err.Error(), http.StatusBadRequest)
        },
        ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
            http.Error(w, err.Error(), http.StatusInternalServerError)
        },
    }}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
    return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
    ssi StrictServerInterface
    middlewares []StrictMiddlewareFunc
    options StrictHTTPServerOptions
}


    
    // GetState operation middleware
    func (sh *strictHandler) GetState(w http.ResponseWriter, r *http.Request) {
        var request GetStateRequestObject

        

        handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
            return sh.ssi.GetState(ctx, request.(GetStateRequestObject))
        }
        for _, middleware := range sh.middlewares {
            handler = middleware(handler, "GetState")
        }

        response, err := handler(r.Context(), w, r, request)

        if err != nil {
            sh.options.ResponseErrorHandlerFunc(w, r, err)
        } else if validResponse, ok := response.(GetStateResponseObject); ok {
            if err := validResponse.VisitGetStateResponse(w); err != nil {
                sh.options.ResponseErrorHandlerFunc(w, r, err)
            }
        } else if response != nil {
            sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
        }
    }
: api.go:203:1: expected declaration, found https
api/package.go:7: running "oapi-codegen": exit status 1
make: *** [gen] Error 1
```

### openapi.yaml
```
openapi: "3.0.0"
info:
  title: Bar
  description: Foo
  version: 1.0.11
servers: 
  - url: http://localhost:9999/api
paths:
  /edges:
    get:
      operationId: getState
      responses:
        "200":
          description: successful operation
components:
  schemas:
    State:
      type: string
      enum: [ONLINE, OFFLINE]
```

### Config file:
```
package: api
generate:
  models: true
  chi-server: true
  strict-server: true
  client: true    # <-- If this is `false` the generation will work
compatibility:
  always-prefix-enum-values: true
output: generated.go
output-options:
  user-templates:
    client-with-responses.tmpl: https://raw.githubusercontent.com/deepmap/oapi-codegen/master/pkg/codegen/templates/client-with-responses.tmpl # <-- generation will work without user-template
```

### Command
```
//go:generate oapi-codegen -config oapi-codegen.yaml openapi.yaml
```

This will also fail for local files!

**Comment by lukaskirner** [comment] 2023-09-11 14:51
Seems like it prints the url above the `ServerInterface`. Which will result into invalid syntax:

```
...
https://raw.githubusercontent.com/deepmap/oapi-codegen/master/pkg/codegen/templates/client-with-responses.tmpl// ServerInterface represents all server handlers.
type ServerInterface interface {
...
```

**Comment by jamietanna** [comment] 2024-01-25 14:48
Thanks for raising this! It looks like there may have been an unrelated change that has now fixed this as I can't reproduce - gimme a shout if it's still affecting you.

For reference, I'm checked out on `3bf5755366704a1594410d6a7aa7aab966d04c6e` and with the following change:

```diff
diff --git examples/custom-client-type/cfg.yaml examples/custom-client-type/cfg.yaml
index 6f52fb3d..8513f138 100644
--- examples/custom-client-type/cfg.yaml
+++ examples/custom-client-type/cfg.yaml
@@ -5,3 +5,5 @@ generate:
   client: true
 output-options:
   client-type-name: CustomClientType
+  user-templates:
+    client-with-responses.tmpl: https://raw.githubusercontent.com/deepmap/oapi-codegen/v1.15.0/pkg/codegen/templates/client-with-responses.tmpl # <-- generation will work without user-template
```

I can't see any compilation errors.

**Closed by jamietanna** 2024-01-25 14:48 UTC
Labels: bug
